# Generated by Django 4.1.1 on 2022-11-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=500, verbose_name='Menssagem')),
                ('data_2', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_popular', models.CharField(max_length=255, verbose_name='Nome popular')),
                ('nome_cientifico', models.CharField(max_length=255, verbose_name='Nome científico')),
                ('especie', models.CharField(max_length=255, verbose_name='Espécie')),
                ('altura_max', models.CharField(max_length=255, verbose_name='Altura máxima')),
                ('diametro', models.CharField(max_length=255, verbose_name='Diâmetro nominal (cm)')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('local', models.CharField(max_length=255, verbose_name='Localização')),
                ('clima', models.CharField(max_length=255, verbose_name='Clima')),
                ('regiao', models.CharField(max_length=255, verbose_name='Região')),
                ('origem', models.CharField(max_length=255, verbose_name='Origem')),
                ('latitude', models.CharField(max_length=255, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=255, verbose_name='Longitude')),
                ('extincao', models.CharField(choices=[('Em Extinção', 'Em Extinção'), ('Abundante', 'Abundante')], max_length=255, verbose_name='Ameaça de extinção')),
                ('desc', models.TextField(blank=True, verbose_name='Texto descritivo')),
                ('data_1', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('image', models.ImageField(upload_to='', verbose_name='Upload imagem')),
            ],
        ),
    ]
